version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: fitproof_postgres
    environment:
      POSTGRES_DB: fitproof_dev
      POSTGRES_USER: fitproof_user
      POSTGRES_PASSWORD: fitproof_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitproof_user -d fitproof_dev"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local